In [100]:
import pandas as pd

data = pd.read_csv("employees_dirty.csv")

,employee_id,name,age,gender,department,salary,experience,city,hire_date,email,performance_score
4,1005,John Smith,45.0,Male,Management,5200,20.0,Frankfurt,2010-01-10,john@gmail.com,95.0
9,1010,David Brown,39.0,Male,Management,4800,15.0,Frankfurt,2015-06-30,david@gmail.com,93.0
16,1017,Tom Becker,41.0,Male,Management,5100,18.0,Frankfurt,2012-12-01,tom@gmail.com,NaN
22,1023,Daniel Koch,38.0,Male,Management,5000,14.0,Frankfurt,2014-08-30,daniel@gmail.com,96.0

In [106]:
data[~data["gender"].isin(["Male", "Female"])]

,employee_id,name,age,gender,department,salary,experience,city,hire_date,email,performance_score
5,1006,Amir Rezaei,27.0,male,Data Science,2400,3.0,Munich,2022-07-19,amir@gmail.com,85.0
8,1009,Lisa Muller,28.0,F,DevOps,2900,5.0,Hamburg,2021-04-18,lisa@gmail.com,89.0